### ISSUE TITLE
Terminal-compatible client

### ISSUE THREAD

**Issue by randomairborne** [FerrisChat/FerrisChat#10]
One of the major lackings of Discord is the inability to create custom clients, and i think a command line client would be useful and a good example of how to implement the clients.

**Comment by hydrostaticcog** [comment]
The API will be open to anyone with a token, so the ability to create custom clients will be there. We may not *support* them, nor are they high on our priority list.

**Comment by hydrostaticcog** [comment]
Also please ask us questions in the Discord (irony) so we don't have a ton of issues open.
