### ISSUE TITLE
Add toolchain info

### ISSUE THREAD

**Issue by TheBlackfurGuy** [FerrisChat/FerrisChat#13]
Hello, since building on stable doesn't work due to the #[feature] flag being used. A toolchain file should be added telling cargo to use the nightly or beta version.

**Comment by hydrostaticcog** [comment]
Hi, a `rust-toolchain` file is being added as we speak. Thanks for bringing this to light! Just a note for the future, please open an issue in either the [Client](https://github.com/FerrisChat/Client) or the [Server](https://github.com/FerrisChat/Server) repo, depending on the program where the bug occurs. This repo is being deprecated (see #12)
