### ISSUE TITLE
Make github organization and have seperate client and server repos

### ISSUE THREAD

**Issue by randomairborne** [FerrisChat/FerrisChat#9]

**Comment by hydrostaticcog** [comment]
I actually disagree on this, the client and server should definitely be in the same repo (you can change which one you build in the CLI, and most users will use a pre-constructed binary. As for the GH organization, that is up to @tazz4843.

**Comment by randomairborne** [comment]
if they’re in the same repo, building it yourself requires git cloning a lot more code, and then we get a shorter URL

**Comment by hydrostaticcog** [comment]
not really

**Comment by randomairborne** [comment]
i mean, does it not make it more organized?

**Comment by hydrostaticcog** [comment]
client is `cargo build --release --bin client`. Server is `DATABASE_URL="postgres://" cargo build --release --bin server`

**Comment by randomairborne** [comment]
Alright, cool.

**Comment by hydrostaticcog** [comment]
not really. client and server are separated into different modules. its actually more efficient to use the same repo, since client and server use some of the same modules.

**Comment by tazz4843** [comment]
we could make a central repo containing the common modules, and split client and server into their own

i personally think splitting them would be a good idea, reducing compile time for the non-common modules
